# config/packages/security.yaml
security:
    enable_authenticator_manager: true

cors:
    paths:
        '^/api/':
            allow_origin: ['*']
            allow_headers: ['Content-Type', 'Authorization']
            allow_methods: ['GET', 'POST', 'PUT', 'DELETE']
            max_age: 3600
